### ISSUE TITLE
喜欢这个风格，我如果自己打包的话，执行bin下的build.sh即可是吧？

### ISSUE THREAD

**Issue by dumbsheep1990** [iimeta/fastapi#1]

**Comment by dumbsheep1990** [comment]
但是打包完执行报了如下错误：./bin/fastapi-admin: line 1: syntax error: unexpected "("

**Comment by dumbsheep1990** [comment]
添加了GOOS=linux GOARCH=amd64貌似可以了

**Comment by dumbsheep1990** [comment]
修改静态文件怎样生效？打包完还是默认样式

**Comment by iimeta** [comment]
> 修改静态文件怎样生效？打包完还是默认样式

https://github.com/iimeta/fastapi-web
前端代码仓库，需要最新的要自己编译一下
