### ISSUE TITLE
公益站打不开了？

### ISSUE THREAD

**Issue by myvica** [iimeta/fastapi#3]
这个关闭了吗？
> ### 公益站点
> - API地址: https://api.free.fastapi.ai/
> - 注册后请联系作者领取1000万额度

**Comment by iimeta** [comment]
> 这个关闭了吗？
> > ### 公益站点
> > - API地址: https://api.free.fastapi.ai/
> > - 注册后请联系作者领取1000万额度
> 

可以了，如果还打不开请刷新一下dns缓存

**Comment by myvica** [comment]
可以了，感谢！
